# Generated by Django 6.0.2 on 2026-02-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('recruiter', 'Recruiter')], default='freelancer', max_length=20),
            preserve_default=False,
        ),
    ]
