# Generated by Django 6.0.2 on 2026-02-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_bio_remove_user_skills_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('recruiter', 'Recruiter')], default='freelancer', max_length=20),
        ),
    ]
