# Generated by Django 6.0.2 on 2026-02-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_freelancerprofile_job_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
