# Generated by Django 6.0.2 on 2026-02-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
