# Generated by Django 6.0.2 on 2026-02-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_job_options_job_created_at_job_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, default=''),
        ),
    ]
